spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 0HGuvWq8DoXxjiRrWVF0
            client-secret: sNAeXNavsj
            redirect-uri:  http://localhost:9000/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-id: f2b36313e9aebb13c0a5619c56c29c9b
            client-secret: RZRkkeazbCZ3Ux6IoDY84Lvw697CPuKC
            redirect-uri: http://localhost:9000/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile
              - accunt_email
          google:
            client-id: 201578425726-vlvsingacdtr43l1rqu9tsoar667lkgu.apps.googleusercontent.com
            client-secret: W_22w3sHphrmx6Sl3gEK3kt0
            scope:
              - profile
              - email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response




#spring.security.oauth2.client.registration.google.client-id=201578425726-vlvsingacdtr43l1rqu9tsoar667lkgu.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=W_22w3sHphrmx6Sl3gEK3kt0
#spring.security.oauth2.client.registration.google.scope=profile,email
# kakao
# f2b36313e9aebb13c0a5619c56c29c9b
# RZRkkeazbCZ3Ux6IoDY84Lvw697CPuKC

# Google
# 201578425726-vlvsingacdtr43l1rqu9tsoar667lkgu.apps.googleusercontent.com
# W_22w3sHphrmx6Sl3gEK3kt0

# Naver
# 0HGuvWq8DoXxjiRrWVF0
# sNAeXNavsj

