server:
  port: 9000 # 01. 디폴트는 8080

spring:
  application:
    name: demo

  # 02. 데이터 연결해 주는 부분
  datasource:
    platform: mysql
    # url: jdbc:mysql://RDS엔드포인트:3306/DB스키마명?autoReconnect=true
    # autoReconnect : 시간이 지나면 DB 연결이 자동으로 끊기는데 이를 막기 위함
    url: jdbc:mysql://baemindb.ckywccfsj4o1.ap-northeast-2.rds.amazonaws.com:3306/baemin_db?autoReconnect=true
    username: admin
    password: guswjd35
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 데이터 추적
